// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using poneaChallenge.Models;

namespace server.Migrations
{
    [DbContext(typeof(TaskIssuedContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("poneaChallenge.Models.TaskIssued", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<int>("Precidence")
                        .HasColumnType("integer");

                    b.Property<int>("StartedOrStopped")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("TasksIssued");
                });
#pragma warning restore 612, 618
        }
    }
}
